version: '3'
services:
    wordpress_db:
        image: mysql:5.7
        restart: always
        volumes:
            - "./server/database:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD:  wordpress
            MYSQL_DATABASE: danish-app
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    wordpress:
        image: wordpress:latest
        depends_on:
            - wordpress_db
        links:
            - wordpress_db
        ports:
            - 8000:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: wordpress_db:3306
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: danish-app
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: |
                define('FS_METHOD', 'direct');
        volumes:
            - "./src/:/var/www/html/wp-content/plugins/hfc-code"
            - "./wordpress/:/var/www/html"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - wordpress_db
        links:
            - wordpress_db:mysql
        ports:
            - 8181:80
        restart: always
        environment:
            MYSQL_USERNAME: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
            PMA_HOST: mysql
